app = "dpa-fly-backend-ufegxw"
primary_region = "syd"

[deploy]
  release_command = ""
  strategy = "immediate"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false     # ✅ Keep the machine running
  min_machines_running = 1       # ✅ Ensures no cold starts
  processes = ["app"]

  [http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.3", "TLSv1.2"]

  [[http_service.checks]]
    method = "get"
    path = "/"
    protocol = "http"
    interval = "10s"
    timeout = "2s"
