app = "dpa-fly-backend"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
